# Generated by Django 4.2.3 on 2023-07-21 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('passfail', 'Pass/Fail'), ('truefalse', 'True/False'), ('float', 'Floating point decimal'), ('int', 'Integer'), ('char', 'Short text (char)'), ('text', 'Long text'), ('date', 'Date'), ('time', 'Time')], default='char')),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedure_writer.procedure')),
            ],
        ),
        migrations.AddConstraint(
            model_name='datafield',
            constraint=models.UniqueConstraint(fields=('procedure', 'name'), name='unique_name_within_procedure'),
        ),
    ]
