# Generated by Django 4.2.3 on 2023-07-21 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_writer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField(default=0)),
                ('reference_document_title', models.CharField(blank=True, help_text='Please include document revision number (if applicable).', max_length=200)),
                ('reference_document_URL', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='datafield',
            name='unique_name_within_procedure',
        ),
        migrations.AddConstraint(
            model_name='datafield',
            constraint=models.UniqueConstraint(fields=('procedure', 'name'), name='unique_name_within_procedure', violation_error_message='Field name already used within the procedure.'),
        ),
        migrations.AddField(
            model_name='procedurerevision',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='procedure_writer.procedure'),
        ),
        migrations.AddConstraint(
            model_name='procedurerevision',
            constraint=models.UniqueConstraint(fields=('procedure', 'revision_number'), name='unique_revision_number_within_procedure', violation_error_message='Revision number already used.'),
        ),
    ]
