# Generated by Django 4.2.3 on 2023-07-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_writer', '0002_procedurerevision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedurerevision',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
