# Generated by Django 4.2.3 on 2023-07-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_writer', '0003_procedurerevision_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedurerevision',
            name='is_published',
            field=models.BooleanField(default=False, help_text='If the box is unchecked, the revision is in draft mode.', verbose_name='Publish revision'),
        ),
    ]
