# Generated by Django 4.2.3 on 2023-07-27 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_writer', '0004_alter_procedurerevision_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafield',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_fields', to='procedure_writer.procedure'),
        ),
    ]
