# Generated by Django 4.2.3 on 2023-07-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_writer', '0006_alter_procedure_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='datafield',
            name='unique_name_within_procedure',
        ),
        migrations.AlterField(
            model_name='datafield',
            name='field_type',
            field=models.CharField(choices=[('passfail', 'Pass/Fail'), ('truefalse', 'True/False'), ('float', 'Decimal (float)'), ('int', 'Integer'), ('char', 'Short text (char)'), ('text', 'Long text'), ('date', 'Date'), ('time', 'Time')], default='char'),
        ),
        migrations.AddConstraint(
            model_name='datafield',
            constraint=models.UniqueConstraint(fields=('name', 'procedure'), name='unique_name_within_procedure'),
        ),
    ]
